### PR TITLE
Add support for arrays and RND()

### PR DESCRIPTION
**Pull request by jbush001**

### CODE REVIEW

**Comment by rollbear** [comment]
Something like this should be doable. Extremely sketchy, but using variadic templates removes the need for predefined constructors and operator() with different numbers of parameters. It makes for somewhat messy logic, though.

class array
{
public:
  template <typename ... T>
  array(T ... t) : index_multipliers{(1U+t)..., 1},
    vs(std::accumulate(std::begin(index_multipliers),
                       std::end(index_multipliers),
                       1U,
                       [](std::size_t i, std::size_t j){return i*j;}))
  {
  }
  template <typename ... T>
  variant& operator()(T ... t)
  {
    if (sizeof...(t) != index_multipliers.size() - 1)
      dimension_error(); // dies
    std::size_t idx[] { std::size_t(t)... };
    auto i = sizeof...(t);
    // calculate offset in loop and return
    return vs[offset];
  }
private:
  std::vectorstd::size_t index_multipliers;
  std::vector<variant> vs;
};

Can the dimensions be variables? I don't remember...

**Comment by jbush001** [comment]
Just checked, Apple BASIC did allow variables as dimensions, but I think it's a useful feature regardless.

**Comment by rollbear** [comment]
Hello again. Did you run out of steam, or did we misunderstand each other? I'm happy to accept your PR as is, if you want to, although I'd prefer a more generalized one. On the other hand, I guess I can generalize it myself if you prefer it that way.

**Comment by jbush001** [comment]
Sorry for the delay.  I like your idea, but haven't had the chance to sit down and update it (I haven't used variadic templates before, so I'd probably need to spend some time monkeying around to figure them out). I don't mind if you want to reimplement this feature the right way.

**Pull request merged**
