### PR TITLE
Do.. While and structured examples

### PR DESCRIPTION
**Pull request by MCSH**
Request to add DO ... LOOP UNTIL and DO... LOOP WHILE commands. 
( https://en.wikipedia.org/wiki/BASIC#Typical_BASIC_keywords )

Also a separate folder for examples.

### CODE REVIEW

**Comment by rollbear** [comment]
Just a note to let you know I've seen this. Busy all day today. Will look into it tomorrow.

I'm thinking of adding these under a separate #ifdef, so you can chose BASIC dialect at compile time, what do you think?

**Comment by MCSH** [comment]
It's alright I know a fellow programmer can be busy.

What about adding different headers instead of ifdef blocks?

**Comment by rollbear** [comment]
Good idea. Can you adapt your PR to a separate header, "structured_basic.hpp" (or something such) which includes the current header and adds your stuff? Add a few words to the README too.

**Comment by MCSH** [comment]
Sure.

**Comment by MCSH** [comment]
Done.

**Comment by rollbear** [comment]
Stole a few minutes from work ;-)

Looks cool. Still a bit nervous about using scopes, but since I have no concrete examples of when it causes problems, I'm letting them be. Should problems arise, the functionality can always be implemented in similar vein as the FOR-loop.

**Comment by MCSH** [comment]
Thanks!

I really doubt the possibility of the scopes making any problem, I've used similar #define before.

**Pull request merged**
